apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    app: mydeployment
  ports:
    - port: 80          # service port
      targetPort: 80    # container port (your nginx EXPOSE 80)
      nodePort: 30080   # external port (30000-32767), optional
