# argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invoice-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Hai-NgoTruong/argocdlab.git 
    targetRevision: main # track on main branch
    path: invoice  
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: invoice-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
